### ISSUE TITLE
Trying to implement IFGroup using constant current source

### ISSUE THREAD

**Issue by mihirpatankar** [fzenke/auryn#30]
I am trying to implement a code for IFGroup (Leaky integrate and fire neurons) for a single neuron using a constant current input. I was expecting the output to be periodic in nature with the neuron firing at regular intervals. But the output voltage measured using VoltageMonitor shows a constant output at -0.07 which seems to be the default value. I am setting the current to 10.0 using CurrentInjector, running the simulation for 1.0s and using the default parameters for IFGroup. Also, changing the current value or the time of simulation does not affect the output voltage.

Any help would be appreciated.

**Comment by fzenke** [comment]
Thanks for reporting this. This was a bug relate to some legacy code which is now fixed in the latest master branch commit and head of the develop branch. I added a working example for CurrentStimulator 'sim_current_inject' with the output shown below.

![mem](https://user-images.githubusercontent.com/5672284/31222745-1bba523e-a9c0-11e7-9221-a9ce2de6f12d.png)
