### ISSUE TITLE
Support for ppc64, arm, s390x?

### ISSUE THREAD

**Issue by sanjayankur31** [fzenke/auryn#33]
Hi @fzenke 

I've been working on including Auryn in [NeuroFedora](https://neuro.fedoraproject.org). While it builds without issue on x86_64 and i686, it [does not build on ppc64, s390x, and arm architectures](https://koji.fedoraproject.org/koji/taskinfo?taskID=32866703). The build errors point to code that does not work on these. So, would it be correct to assume that Auryn does not support these (and if so, is there a plan to support them in the future?)?

Thanks very much!

**Comment by sanjayankur31** [comment]
I can get it to build on ppc64 by using the `-DNO_WARN_X86_INTRINSICS` compiler instruction, but not yet on arm/s390x. New build here: https://koji.fedoraproject.org/koji/taskinfo?taskID=32866962

**Comment by fzenke** [comment]
Thanks for reporting this and thanks for the initiative with NeuroFedora. It would be great to also support arm and ppc64. As you point out yourself the problem is related to the use of x86 intrinsics and due to the related use of memory alignment. I think the easiest would be to disable x86 intrinsic operations (like SSEx) when compiling for these architectures. Normally this should be achieved by commenting out the line

    // #define CODE_USE_SIMD_INSTRUCTIONS_EXPLICITLY

under src/auryn/auryn_definitions.h. However, I just saw that this does not automatically remove the import of the "include x86intrin.h" and that it caused some havoc in other places. I just pushed several fixes into master and develop which should resolve these issues such that the suggested change above alone should indeed remove all pointers to x86. Let me know how it goes.

**Comment by sanjayankur31** [comment]
Thanks for the quick fix! I'll build from the git snapshot and confirm the fix ASAP. It'll mean providing the git snapshot in NeuroFedora, though---I hope that's OK?

**Comment by fzenke** [comment]
Fine by me. If you prefer I can make it a maintenance release. Let's see first whether the did works. Do you have an arm or PPC emu or machine to run ```run_network_tests.sh``` by any chance or are you crosscompiling?

**Comment by sanjayankur31** [comment]
Fedora provides machines for builds---we don't crosscompile. I've been able to run the unit tests, but not the network_tests in my builds yet. We have access to test machines, though, so I'll run everything there to check if it all works fine and report back to you (https://fedoraproject.org/wiki/Test_Machine_Resources_For_Package_Maintainers)

If it all works, a maintenance release would be nice :)

**Comment by sanjayankur31** [comment]
Hi @fzenke 

The fix looks good. After commenting the line in `auryn_definitions.h`, the build and tests (unit and network) all finish successfully on ppc64le and armv7. We don't have a test s390x machine, unfortunately so I couldnt test that out.

If you could make a new minor release when you have the time, I'll update the NeuroFedora package.

Thanks very much.

**Comment by fzenke** [comment]
Done. v0.8.2. Thanks heaps for supporting Auryn!

**Comment by sanjayankur31** [comment]
Auryn is now available in NeuroFedora: https://docs.fedoraproject.org/en-US/neurofedora/compneuro-tools/ :champagne: 

It's currently in testing, and will go stable by next week.
