### ISSUE TITLE
Add a weight checker

### ISSUE THREAD

**Issue by sanjayankur31** [fzenke/auryn#9]
Do you think a weight checker would be a nice addition? Similar to the Rate checker, it'll break the run if the weights of a certain synapse set go out of bounds? This will be come in handy when people want to ensure that their simulations stay in certain limits - maybe biologically plausible limits?

**Comment by fzenke** [comment]
Sounds like a great idea indeed! That's exactly why Checkers were
implemented as one of the abstract base classes. Add one, please ;-)

**Comment by sanjayankur31** [comment]
Awesome! I'll work on it and open a pull request when I'm done. Cheers!

**Comment by fzenke** [comment]
Any news on this?

**Comment by ChiaraGastaldi** [comment]
Dear Friedemann,
sorry for the delay, but I am checking better, and I  corrected the plot of the population activity in order to average over the 4 ranks, while before I was only considering rank 0.  In the meantime, I am also trying to make an analogue simulation but for only 3 patterns (for example excluding the triangle).
I will collect all the result and post the plots tomorrow :-)
Thanks a lot!
Cheers
Chiara
________________________________
Da: Friedemann Zenke [notifications@github.com]
Inviato: martedì 8 dicembre 2015 7.27
A: fzenke/auryn
Oggetto: Re: [auryn] Add a weight checker (#9)


Any news on this?

**Comment by fzenke** [comment]
Just implemented a WeightChecker. It's in the develop branch in will be included in the next release.
